### ISSUE TITLE
Publish 3.0.0 release

### ISSUE THREAD

**Issue by Levdbas** [smithfield-studio/acf-svg-icon-picker#13]
**Before publishing 3.0.0**
- [ ] #3 
- [x] #8 

**After publishing 3.0.0**
- [ ] #9

**Comment by Levdbas** [comment]
@mike-sheppard , are you able to do #3 and maybe #8 ?  If you need some help we can jump into a quick Teams call.

**Comment by mike-sheppard** [comment]
hey @Levdbas I'm not going to have much time to dedicate to this until we've launched the site we're working on (next week 🤞) please feel free to push any updates & PR's, I'm always happy to review :)

**Comment by mike-sheppard** [comment]
My focus was "just get it working with ACF 6.3" 😅 haha

**Comment by Levdbas** [comment]
Did some last minor things and published the release. Readme is updated as well!
