### ISSUE TITLE
This plugin still required as of ACF 6.3?

### ISSUE THREAD

**Issue by alexander-nitsche-governikus** [smithfield-studio/acf-svg-icon-picker#18]
Hi guys,

since this plugin integrates an icon picker in ACF, which is natively available since ACF v6.3, I wonder if this plugin is still needed. What do you think?

Best regards
Alex

P.S.: Nevertheless I would like to thank you for your work!

**Comment by Levdbas** [comment]
Hi @alexander-nitsche-governikus ,

Since the new icon picker field for ACF doesn't support a good way to easily implement your own icon sets I still use this plugin. Maybe as the native icon picker field gets easier to extend we might rebuild this plugin to fully take advantage of that new field.
