### ISSUE TITLE
[BUG] Can't filter on `Å` and `å`

### ISSUE THREAD

**Issue by Rvervuurt** [smithfield-studio/acf-svg-icon-picker#19]
### Expected Behavior

When searching for a file with the special character `å`, it should show up.

### Actual behavior

When searching for a file with the special character `å`, it is not shown in the popup.

### Steps to reproduce behavior

1. Create a file with name `forhåndsvisning.svg` and add it to the `assets/img/acf/`-folder (see attached file)
2. Search for `forh` and the icon will appear
3. Search for `forhå` and the icon will not appear
![forhåndsvisning](https://github.com/user-attachments/assets/3808cd91-64e9-49b8-8606-53b5ce10d2ca)
![Screenshot 2024-09-23 at 13 19 36](https://github.com/user-attachments/assets/6bbb6d97-8cc7-4b6b-a9a0-f6c56c22c1fa)
![Screenshot 2024-09-23 at 13 19 42](https://github.com/user-attachments/assets/575b1289-5d90-4df1-bfcc-cabaa4a82007)
![Screenshot 2024-09-23 at 13 19 46](https://github.com/user-attachments/assets/20ed8923-b19a-4070-9c62-02f5963ad938)

### Notes

Other special characters like `æ` and `ø` work as expected.

### What version of the plugin are you using?

3.1.2

### What version of WordPress are you using?

6.6.1

### What version of PHP are you using?

8.2

**Comment by mike-sheppard** [comment]
Fixed by @Rvervuurt in #21
