### ISSUE TITLE
How this plugin handles paths.

### ISSUE THREAD

**Issue by Levdbas** [smithfield-studio/acf-svg-icon-picker#22]
Alright, I would like to make some changes on how this plugin handles the directory and file lookups.

What I find strange in the current version is the following:

- plugin defaults to an icon folder inside the plugin folder. This does not make sense because icons will be removed after updates if we ever implement an update mechanism. And who is storing icons in a plugin anyway?
- The there are filters for setting path suffix, path and url. In my opinion, this should only be one, probably a folder path inside your (parent)theme.
- Why can we only check one path? I would like to also have a possibility to add icons in a parent theme for example.
- There is a priority directory lookup, but if you are setting another path currently this directory lookup is not needed and only causes additional file lookups

**My plan**

- [ ] Overhaul filters to only really provide the ones that are needed.
- [ ] Overhaul the way SVG's are getting found and support SVG lookup in parent and child themes where child themes would have precedence over already found files in the parent theme.

This will probably introduce breaking changes. I would like to know how other people are currently using this plugin and where they store their SVGs.

**Comment by mike-sheppard** [comment]
Sounds great! Agree with all your points — the current implementation is far from ideal!

Bit of a mess at the min + haven't had much time to refactor. Here's our WIP theme config, I would love to simplify this during our next build.

```php
// ACF Icon Picker Paths Config
add_filter('acf_icon_path_suffix', fn ($path_suffix) => '/dist/editor/images/icons/admin-picker/');
add_filter('acf_icon_path', fn ($path_suffix) => public_path());
add_filter('acf_icon_url', fn ($path_suffix) => '');
```
