### ISSUE TITLE
Remove fork from repo

### ISSUE THREAD

**Issue by Levdbas** [smithfield-studio/acf-svg-icon-picker#23]
Hauke archives his repository so we can safely unmark this repo as a fork. This will cleanup the Github repo interface a bit.
Can you do that @mike-sheppard ?

**Comment by mike-sheppard** [comment]
Sounds good, popped a request in with GH support to detach the fork 👍

**Comment by mike-sheppard** [comment]
Fork detached from [houke/acf-icon-picker](https://github.com/houke/acf-icon-picker)  ✅
