### ISSUE TITLE
enable auto-update in packagist

### ISSUE THREAD

**Issue by mike-sheppard** [smithfield-studio/acf-svg-icon-picker#3]
- [x] publish to packagist
- [x] update readme with new installation method
- [x] Enable auto update of package
- [ ] Add a suitable license (fix warning on Packagist)

**Comment by Levdbas** [comment]
Hi @mike-sheppard , did you publish packages before to packagist? Let me know if you'll need some help setting this up. This is a good read btw: https://kinsta.com/blog/create-composer-package/

**Comment by Levdbas** [comment]
I've managed to publish the package, but for auto updates We need somebody with organisational access to setup a hook to packagist.org. Let's tackle that when you're available: https://packagist.org/packages/smithfield-studio/acf-svg-icon-picker

**Comment by mike-sheppard** [comment]
amazing! thanks @Levdbas, I'll hopefully find some time this week to dive in; just a bit manic at the moment :)

**Comment by Levdbas** [comment]
No problem! This can wait :)

**Comment by mike-sheppard** [comment]
nice one! I've logged into Packagist, but I don't seem to be able to update. Could you could add me as a maintainer, my Packagist user name is the same as git `mike-sheppard`.

**Comment by Levdbas** [comment]
Just invited you 👍

**Comment by mike-sheppard** [comment]
Perfecto, that was easy - all setup!

**Comment by Levdbas** [comment]
Nice work!
