### ISSUE TITLE
Issue displaying svg icon on the frontend

### ISSUE THREAD

**Issue by alex-kodr** [smithfield-studio/acf-svg-icon-picker#30]
I've added the plugin and changed the path of my icon folder to be theme-folder/assets/images/icons/ using the `acf_svg_icon_picker_folder` filter. I can see icons in admin no problem. I have a repeater field setup inside flexible content. The name of the sub field I'm using is called 'icon'. 

Now in my theme php file I'm grabbing the subfield `$icon = get_sub_field('icon');` and then echoing it `echo $icon;` But for some reason it's not displaying the SVG it's just showing the text name of the SVG file. I can't work out from your documentation how to display the SVG. I've tried `$icon_svg = get_svg_icon($icon);` but this doesn't work. Anything to point me in the right direction would be of great help. Thanks

**Comment by Levdbas** [comment]
Hi @alex-kodr , its correct that you receive only the name of the icon currently when using get_field or get_sub_field. We could change that in a future update where get_field or get_sub_field will hold the SVG directly.

You can use the function as follows:

```php
$icon = get_sub_field('icon');
SmithfieldStudio\AcfSvgIconPicker\get_svg_icon($icon);
```

Be mindful of the namespaced function.

Please let us know if that helps. And if you want to help to improve upon the documentation, feel free to do so.

**Comment by alex-kodr** [comment]
Hi @Levdbas, thanks for the reply. I wasn't sure if I'd missed something from the documentation. Thanks for the above function. I created an if else statement based off the icon name value, because I could get this to display. This solved the issue. It's a great little plugin 👍

**Comment by Levdbas** [comment]
Hi @alex-kodr , I now have a PR in the works to directly output an icon with `get_field` as a setting on the field level. You can track its process here #31 .

And thanks!
